# Generated by Django 4.1.4 on 2023-01-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_likepost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="lastname",
        ),
    ]
